export const Policy = {
  COOLDOWN_DAYS: 7,
  MIN_ITEM_USD: 0.10,
  MIN_BUNDLE_GROSS_USD: 2.0,
  MIN_BUNDLE_NET_USD: 1.0,
  MAX_BUNDLE_SIZE: 30,
  MIN_BUNDLE_SIZE: 10,
  IDEMPOTENCY_TTL_HOURS: 1,
  QUARANTINE_TTL_HOURS: 6,
  RETRY_MAX_ATTEMPTS: 3,
  RETRY_BASE_DELAY_MS: 1000,
  SCHEDULE_TICK_INTERVAL_MS: 60000, // 1 minute
  SCHEDULE_JITTER_MS: 5000 // ±5 seconds
} as const;